spring:
  datasource:
    url: jdbc:mysql://localhost:13306/rao
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always # never | embedded
      schema: classpath:schema.sql

input:
  file: ./files/relatorio.txt
